	%IF %sysfunc(exist(DATAFLDR.TBL_MODEL_INFO&MDLUZER, data)) %THEN
		%DO;

			DATA DATAFLDR.TBL_MODEL_INFO&MDLUZER;
				SET WORK.TBL_INFO_TRANS DATAFLDR.TBL_MODEL_INFO&MDLUZER;
			%END;
		%ELSE
			%DO;

			DATA DATAFLDR.TBL_MODEL_INFO&MDLUZER;
				SET WORK.TBL_INFO_TRANS;
			%END;
	RUN;